packageExtensions:
  express-winston@*:
    dependencies:
      logform: '*'
      winston-transport: '*'
  markdownlint-cli@*:
    dependencies:
      deep-extend: '*'
  typeorm@*:
    dependencies:
      ts-node: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.2.4.cjs
