packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  ts-node-dev@*:
    dependencies:
      node-notifier: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.0.0-rc.2.cjs
